### ISSUE TITLE
implement conversion function for LLA to ECI state vector

### ISSUE THREAD

**Issue by capsulecorplab** [ODU-CGA-CubeSat/orbit-propogator#7]
In order to use the Vinti6 orbit propagator, GPS data (latitude, longitude, & altitude) need to be converted to ECI state vector.

**Comment by capsulecorplab** [comment]
blocked on #6

**Comment by capsulecorplab** [comment]
@G5STER Will this require converting Gregorian time to J2000?

**Comment by G5STER** [comment]
@capsulecorplab Yes, but it is handled through the SOFA library. All we need is the UTC time and we should be good to go
